spring:
  application:
    name: APIGateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: farm-service
              uri: lb://FARM-SERVICE
              predicates:
                - Path=/farm/**

            - id: crop-service
              uri: lb://CROP-SERVICE
              predicates:
                - Path=/crop/**

            - id: weather-service
              uri: lb://WEATHER-SERVICE
              predicates:
                - Path=/weather/**

            - id: ai-service
              uri: lb://AI-SERVICE
              predicates:
                - Path=/ai/**

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG